name: MikroTik SNMP Exporter
version: "0.30.1"
slug: mikrotik_snmp_exporter
description: Prometheus SNMP Exporter for MikroTik RouterOS
url: https://github.com/prometheus/snmp_exporter
arch:
  - amd64
startup: services
boot: auto
init: false
ports:
  9116/tcp: 9116
ports_description:
  9116/tcp: SNMP Exporter
map:
  - type: addon_config
    read_only: false
